version: "3.8" #Versón de la estandarización de docker-compose

#volumes:
#  vol-emqx-data:
#    name: foo-emqx-data
#  vol-emqx-etc:
#    name: foo-emqx-etc
#  vol-emqx-log:
#    name: foo-emqx-log

services: #Nos permite levantar varios contenedores preconfigurados de una sola vez (para no tener que escribir un comando "docker run" gigante)
  
  mongo:
    container_name: mongo
    image: mongo:4.4
    restart: always
    environment:
      TZ: "America/Santiago"
      MONGO_INITDB_ROOT_USERNAME: "devuser" #credenciales de mongo
      MONGO_INITDB_ROOT_PASSWORD: "devpassword"
    volumes:
      - ./mongodata:/data/db #persistencia de datos
    ports:
     - 27017:27017 #puerto estandar de mongo 27017
  
  emqx:
    container_name: emqx
    image: emqx/emqx:4.2.3 #imagen que se va a utilizar, puede ser una versión especifica
    restart: always #Si se cae el servicio se va a levantar de nuevo automáticamente
    ports:
      - 18083:18083 #Dashboard Web de Emqx
      - 8083:8083 #Permite a un sitio web conectarse a MQTT a través del WS
  #  volumes:
  #    - vol-emqx-data:/opt/emqx/data
  #    - vol-emqx-etc:/opt/emqx/etc
  #    - vol-emqx-log:/opt/emqx/log
#
    links:
      - mongo

    environment:
      EMQX_NAME: ioticos-gl
      EMQX_HOST: 127.0.0.1

      TZ: "America/Santiago"
      
      #Default Dash Pass
      EMQX_DASHBOARD__DEFAULT_USER__PASSWORD: "emqxdashpass"
      
      #Mongo Connection
      EMQX_AUTH__MONGO__TYPE: single
      EMQX_AUTH__MONGO__SERVER: "mongo:27017" #detras de "mongo" hay una "ip"
      EMQX_AUTH__MONGO__POOL: 8 #ocho conexiones vivas a mongo

      EMQX_AUTH__MONGO__LOGIN: "devuser"
      EMQX_AUTH__MONGO__PASSWORD: "devpassword"
      EMQX_AUTH__MONGO__AUTH_SOURCE: admin

      EMQX_AUTH__MONGO__DATABASE: "iotgl"
      EMQX_AUTH__MONGO__AUTH_QUERY__COLLECTION: "emqxauthrules"

      EMQX_AUTH__MONGO__SUPER_QUERY__COLLECTION: "emqxauthrules"
      EMQX_AUTH__MONGO__SUPER_QUERY__SUPER_FIELD: "is_superuser"
      EMQX_AUTH__MONGO__SUPER_QUERY__SELECTOR: "username=%u"
      EMQX_AUTH__MONGO__SUPER_QUERY: "off"

      EMQX_AUTH__MONGO__AUTH_QUERY__PASSWORD_HASH: plain
      EMQX_AUTH__MONGO__AUTH_QUERY__PASSWORD_FIELD: "password"
      EMQX_AUTH__MONGO__AUTH_QUERY__SELECTOR: "username=%u"
      #listener.tcp.external.max_connections
      EMQX_LISTENER__TCP__EXTERNAL__MAX_CONNECTIONS: 1000
