version: "3.8" #Versón de la estandarización de docker-compose
services: #Nos permite levantar varios contenedores preconfigurados de una sola vez (para no tener que escribir un comando "docker run" gigante)

  emqx:
    container_name: emqx
    image: emqx/emqx:4.2.3 #imagen que se va a utilizar, puede ser una versión especifica
    restart: always #Si se cae el servicio se va a levantar de nuevo automáticamente
    ports:
      - ${emqxdashport}:18083 #Dashboard Web de Emqx
      - 8083:8083 #Permite a un sitio web conectarse a MQTT a través del WS
    environment:
      #listener.tcp.external.max_connections
      EMQX_LISTENER__TCP__EXTERNAL__MAX_CONNECTIONS: 1000
      